version: "3"

services:
  db:
    image: mongo
    container_name: mongo
    env_file: docker.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit
    volumes:
      - ${WEBAPP_STORAGE_HOME}/_data/mongo:/data/db
      - ${WEBAPP_STORAGE_HOME}/docker/_mongo/fixtures:/import
      - ${WEBAPP_STORAGE_HOME}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 27017:27017

  web:
    build: .
    image: ghcr.io/p2jn/doit
    container_name: doit
    command: bash -c "python manage.py runserver 0.0.0.0:80"
    env_file: docker.env
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/app
    ports:
      - 80:80
    depends_on:
      - db
