version: "3.7"

services:
  mongo:
    image: ghcr.io/p2jn/doit-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit

  postgres_db:
    image: ghcr.io/p2jn/doit-postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=doit
      - POSTGRES_PASSWORD=doit
      - POSTGRES_DB=doit
      - POSTGRES_HOST=postgres_db
    ports:
      - 5432:5432

  web:
    image: ghcr.io/p2jn/doit-develop
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - DOCKER=true
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit
      - POSTGRES_USER=doit
      - POSTGRES_PASSWORD=doit
      - POSTGRES_DB=doit
      - POSTGRES_HOST=postgres_db
    ports:
      - 80:80
    depends_on:
      - mongo
      - postgres_db
      - migration

  migration:
    image: ghcr.io/p2jn/doit-develop
    command: python manage.py migrate
    depends_on:
      - mongo
      - postgres_db
