version: "3"

services:
  mongo_db:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit
    volumes:
      - ${PWD}/_data/mongo:/data/db
      - ${PWD}/docker/_mongo/fixtures:/import
      - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 27017:27017

  postgres_db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=doit
      - POSTGRES_PASSWORD=doit
      - POSTGRES_DB=doit
      - POSTGRES_HOST=postgres_db
    volumes:
      - ${PWD}/_data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    image: doit:latest
    container_name: doit
    command: /bin/sh -c ./script.sh
    environment: 
      - DOCKER=true
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit
      - POSTGRES_USER=doit
      - POSTGRES_PASSWORD=doit
      - POSTGRES_DB=doit
      - POSTGRES_HOST=postgres_db
    ports:
      - 8000:8000
    depends_on:
      - mongo_db
      - postgres_db
