version: "3"

services:
  db:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=doit
    volumes:
      - ${PWD}/_data/mongo:/data/db
      - ${PWD}/docker/_mongo/fixtures:/import
      - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 27017:27017

  web:
    build: .
    image: doit:latest
    container_name: doit
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DOCKER=true
    volumes:
      - ${PWD}:/app
    ports:
      - 80:8000
    depends_on:
      - db
